# Generated by Django 3.0.5 on 2021-04-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_title_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
    ]
