# Generated by Django 3.2 on 2023-06-20 21:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.UsernameValidator()], verbose_name='Никнейм'),
        ),
    ]
