# Generated by Django 2.2.16 on 2022-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, null=True, verbose_name='‘Код подтверждения’'),
        ),
    ]
