# Generated by Django 3.2 on 2024-04-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_yamdbuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(default=2640, max_length=16, verbose_name='Код подтверждения'),
        ),
    ]
