# Generated by Django 3.2 on 2024-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240430_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(default=6098, max_length=16, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой электронной почтой уже существует.'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
