# Generated by Django 3.2.5 on 2021-07-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210720_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
