# Generated by Django 3.0.5 on 2021-07-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210720_1504'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='comments-unique-author',
        ),
    ]
