# Generated by Django 2.2.16 on 2021-09-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Адрес жанра'),
        ),
    ]
