# Generated by Django 3.2 on 2024-02-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='score_between_1_and_10',
        ),
    ]
