# Generated by Django 3.2 on 2023-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231026_1051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='A year value is valid between 1000 and year_now',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 1000), ('year__lte', 2023)), name='A year value is valid between 1000 and year_now'),
        ),
    ]
