# Generated by Django 3.2 on 2023-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231025_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(max_length=4, verbose_name='Год выпуска'),
        ),
    ]
