# Generated by Django 3.2 on 2024-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_genres_title_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'объект «Категория»'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'объект «Жанр»'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название категории'),
        ),
    ]
