# Generated by Django 3.2 on 2023-06-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_titles_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created',), 'verbose_name': ('Комментарий',), 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('created',), 'verbose_name': ('Отзыв',), 'verbose_name_plural': ('Отзывы',)},
        ),
    ]
