# Generated by Django 3.2 on 2023-02-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230215_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='slug',
        ),
    ]
