# Generated by Django 3.2 on 2024-05-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240430_1714'),
        ('reviews', '0005_auto_20240429_1552'),
    ]

    operations = [
    ]
