# Generated by Django 2.2.16 on 2022-05-17 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_auto_20220516_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titles_id',
            new_name='titles',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'titles')},
        ),
    ]
