# Generated by Django 3.2 on 2024-05-04 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_merge_0004_auto_20240430_1714_0005_auto_20240429_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.yamdbuser', verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение рейтинга должно быть больше 1.'), django.core.validators.MaxValueValidator(10, 'Значение рейтинга должно быть меньше 10.')], verbose_name='Рейтинг'),
        ),
    ]
