# Generated by Django 2.2.16 on 2022-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220518_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
