# Generated by Django 3.2 on 2024-05-07 07:24

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'объект «Категория»', 'verbose_name_plural': 'объекты «Категорий»'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'объект «Жанр»', 'verbose_name_plural': 'объекты «Жанров»'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
