# Generated by Django 3.2 on 2024-05-07 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20240507_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='reting',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Значение рейтинга должно быть больше 1.'), django.core.validators.MaxValueValidator(10, 'Значение рейтинга должно быть меньше 10.')], verbose_name='Рейтинг'),
        ),
    ]
