# Generated by Django 3.2 on 2024-05-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_title_reting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='reting',
            new_name='rating',
        ),
    ]
